-- Banking Agent Schema Definition
-- Database: PostgreSQL

-- 1. Enable pg_trgm extension for fuzzy text search on names (optional but good for "Did you mean..?")
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2. Products Table (Master List)
-- Handles both CSV imports and Doc Extractions
CREATE TABLE IF NOT EXISTS products (
    product_id SERIAL PRIMARY KEY,
    
    -- Core Identity
    bank_name VARCHAR(50) NOT NULL,       -- e.g., 'SBI', 'HDFC'
    category VARCHAR(50) NOT NULL,        -- e.g., 'Credit Card', 'Home Loan', 'Scheme'
    product_name VARCHAR(150) NOT NULL,   -- e.g., 'SBI Aurum', 'HDFC Regalia'
    
    -- "Unified Index" Metadata
    source_type VARCHAR(20) NOT NULL,     -- 'csv', 'extracted_doc'
    source_file VARCHAR(255),             -- Filename e.g. 'sbi_products.csv' or 'hdfc_biz_black_launch.md'
    
    -- FLexible Attributes (The Enterprise Enabler)
    -- Stores: Fees, Rates, Eligibility, Rewards, etc. as JSON
    -- Example: {"annual_fee": 499, "reward_rate": "3.3%", "lounge_access": true}
    attributes JSONB,
    
    -- Hybrid Search Helper
    -- A summary generated by LLM during ingestion, useful for keyword search SQL queries
    summary_text TEXT,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints to prevent duplicates
    CONSTRAINT unique_bank_product UNIQUE (bank_name, product_name)
);

-- 3. Indexes for Performance

-- A. Filter Index: "Count all HDFC Loans"
CREATE INDEX IF NOT EXISTS idx_products_filter ON products (bank_name, category);

-- B. JSON Attribute Index: "Find cards with fee < 500"
-- GIN index allows high-speed querying inside the JSONB blob
CREATE INDEX IF NOT EXISTS idx_products_attr ON products USING gin (attributes);

-- C. Text Search Index: "Find products matching 'Travel'"
CREATE INDEX IF NOT EXISTS idx_products_search ON products USING gin(to_tsvector('english', product_name || ' ' || summary_text));


-- 4. Analytics / Missed Queries
CREATE TABLE IF NOT EXISTS interaction_logs (
    log_id SERIAL PRIMARY KEY,
    user_id VARCHAR(100), -- Can be session_id
    query_text TEXT,
    intent_detected VARCHAR(50),
    response_generated TEXT,
    is_missed_query BOOLEAN DEFAULT FALSE,
    feedback_score INT,   -- 1 (Thumbs Down) or 5 (Thumbs Up)
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. User Applications (For Agent Workflows)
-- Stores the state of a user's application (e.g., Credit Card Application)
CREATE TABLE IF NOT EXISTS user_applications (
    application_id SERIAL PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    bank_name VARCHAR(50),
    product_name VARCHAR(150),
    status VARCHAR(50), -- 'INIT', 'KYC_PENDING', 'DOCS_UPLOADED', 'SUBMITTED', 'REJECTED'
    
    -- Current State of the Agent Workflow
    agent_state VARCHAR(50), -- e.g., 'WAITING_FOR_PAN'
    
    -- Data collected so far
    collected_data JSONB,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
